blank_issues_enabled: true
contact_links:
  - name: 📚 Documentação
    url: https://github.com/cohab-minas/.github
    about: Consulte a documentação oficial da organização
  - name: 💬 Discussões
    url: https://github.com/orgs/cohab-minas/discussions
    about: Participe de discussões com a comunidade
